events {}
http {
    # Редирект с www на голый домен (HTTP)
    server {
        listen 80;
        server_name www.nodohub.ru;
        return 301 https://nodohub.ru$request_uri;
    }

    # Редирект с HTTP на HTTPS для голого домена
    server {
        listen 80;
        server_name nodohub.ru;
        return 301 https://$host$request_uri;
    }

    # Редирект с www на голый домен (HTTPS)
    server {
        listen 443 ssl;
        server_name www.nodohub.ru;
        ssl_certificate /etc/ssl/certs/fullchain.pem;
        ssl_certificate_key /etc/ssl/private/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        return 301 https://nodohub.ru$request_uri;
    }

    # Основной сайт
    server {
        listen 443 ssl;
        server_name nodohub.ru;

        ssl_certificate /etc/ssl/certs/fullchain.pem;
        ssl_certificate_key /etc/ssl/private/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;

        client_max_body_size 10M;   # ← теперь 5M

        location / {
            proxy_pass http://nodohub:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}